### ISSUE TITLE
ddescriber fails on readonly file

### ISSUE THREAD

**Issue by quantumcheese** [andresdominguez/ddescriber#7]
We use Perforce, which leaves all files readonly until they are being edited.  I would love if ddescriber would hook into IntelliJ's existing prompt to checkout/edit a file, rather than silently fail to mark fdescribe/xdescribe/fit/xit etc.

Stack trace:

```
Attempt to modify read-only document
com.intellij.openapi.editor.ReadOnlyModificationException: Attempt to modify read-only document
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:546)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:536)
	at com.karateca.ddescriber.ActionUtil.changeSelectedLine(ActionUtil.java:93)
	at com.karateca.ddescriber.ActionUtil.access$000(ActionUtil.java:16)
	at com.karateca.ddescriber.ActionUtil$2.run(ActionUtil.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at com.karateca.ddescriber.ActionUtil$3.run(ActionUtil.java:73)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at com.karateca.ddescriber.ActionUtil.runWriteActionInsideCommand(ActionUtil.java:70)
	at com.karateca.ddescriber.ActionUtil.changeTestList(ActionUtil.java:53)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction.showDialog(JasmineDescribeReplaceAction.java:91)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction.access$000(JasmineDescribeReplaceAction.java:24)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction$1.stateChanged(JasmineDescribeReplaceAction.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy123.stateChanged(Unknown Source)
	at com.karateca.ddescriber.model.JasmineFile$1.run(JasmineFile.java:40)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:843)
	at com.karateca.ddescriber.ActionUtil.runReadAction(ActionUtil.java:24)
	at com.karateca.ddescriber.model.JasmineFile.buildTreeNodeAsync(JasmineFile.java:36)
	at com.karateca.ddescriber.JasmineDescribeReplaceAction.actionPerformed(JasmineDescribeReplaceAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by quantumcheese** [comment]
This is on Win7, IntelliJ IDEA 2016.2 Ultimate (but I'm pretty sure it used to happen on v15 as well).

**Comment by andresdominguez** [comment]
Thank you for reporting this issue. A fix is on the way

**Comment by andresdominguez** [comment]
@quantumcheese I need your help to test this change. Please do the following:

* https://github.com/andresdominguez/ddescriber/tree/check-readonly-status
* Download ddescriber.jar
* Install from jar file.

I will push the change to jetbrains once you give me the green light.

**Comment by quantumcheese** [comment]
Now prompts to clear readonly state as expected.  Thank you!

**Comment by andresdominguez** [comment]
Please update to 3.4 from the jetbrains repository tomorrow
